### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by cpauvert** [mangal-interactions/contribute#6]
### Type of error

other

### Dataset name (or id)

Cohen_2003

### Description of the problem

Hi,
I was just looking at your GloBI indexed record at https://www.globalbioticinteractions.org/references?interactionType=interactsWith&sourceTaxon=Bacteria and noticed that the reference Cohen_2003 was the raw BibTeX rather than the correctly formatted reference (see the 3rd row in the attached screenshot)

![Capture d’écran_2021-11-30_18-02-02](https://user-images.githubusercontent.com/12406679/144094744-71985572-e3f8-43d8-b4ab-ce97f0f4a93b.png)

### How to fix the problem

I look to around to manually edit the indexed reference but could not found anything, so I guess opening an issue was better just to highlight the problem.

Best,
Charlie

**Comment by tpoisot** [comment]
We store the references as bibtex, this is a GLOBI issue.
